# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day24.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 171)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 50, 80, 80))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 120, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(160, 80, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 40, 60, 16))
        self.label_4.setObjectName("label_4")
        self.text_pos = QtWidgets.QTextEdit(Form)
        self.text_pos.setGeometry(QtCore.QRect(230, 30, 131, 31))
        self.text_pos.setObjectName("text_pos")
        self.text_rgb = QtWidgets.QTextEdit(Form)
        self.text_rgb.setGeometry(QtCore.QRect(230, 70, 131, 31))
        self.text_rgb.setObjectName("text_rgb")
        self.text_css = QtWidgets.QTextEdit(Form)
        self.text_css.setGeometry(QtCore.QRect(230, 110, 131, 31))
        self.text_css.setObjectName("text_css")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Color"))
        self.label_2.setText(_translate("Form", "CSS:"))
        self.label_3.setText(_translate("Form", "RGB:"))
        self.label_4.setText(_translate("Form", "Position:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
